language: python
python:
  - '2.7'
  - '3.5'
  - '3.6'
install:
  - python setup.py install
  - pip install flake8
script:
  - flake8
  - python setup.py test
deploy:
    provider: pypi
    user: mdmedley
    distributions: sdist bdist_wheel
    password:
    secure: Tod47Bo2MxJ/Mnpv1MoG735pfYHx451VKv2m01Rzb4qGM9A0IKiwV9vtdkiabpHoaty459V4iMExv63tImn2iktCN3Gr1K1Hw5vxNgA2i7a4axU2Yiil6F3kY2I02p5vHuN7ZptGv54ztFiq+zcZHz9KEbIEikN14zMIIywTonX9gd+nbuT4m+JbdleNlcR9xrVK34Hehkn8tua704PS7k476wHKDNvjtFCSw905GU0Y0PnbD6nqZA8dbmNErg67nEYrlUamn2bMvsq76nqgQ3RF4g+tlME3OnXN4gW2HP3Dj1NIQziDCaTfXkhvn7E1fQqKbxLdaN646u43jPJC6nK4TgOpWivSX9bTw4bRTuwiokLDEunSNSI9LRydQRk34VM4xJ3OIc58muXkgKfa331c2DbwjrVZ4SxguopbPasyM3y04+XMRriAfDToHvTTOTPf7U9U5zomUzDQDWJYj8lLwx4DXjIQvuONzclQ82TS7kJk0U9b+d/i/ERL+vGADpTzONywYuPtQTUpK0rJxV0qjUxfnJINagDjs7ISa1wdwex9aVp/C5+jehozs/gW1WnM0kYuck8RYm05SFk+Rbp5zoQvieQMb1zjy44ONAhCcUZQ2JOeBipjnLlPdeSHttqt/mB+QK4BwKUxwnDfdvq77rKXrS5KVVgthC9pe1I=
    on:
      branch: master
      tags: true
      condition: $TRAVIS_PYTHON_VERSION = "2.7"
      repo: mdmedley/cache_me_outside
